-- hds header_start
--
-- VHDL Entity AES_Sound_1.AES_Dec_main_contrl.symbol
--
-- Created:
--          by - Mostafa.UNKNOWN (MOSTAFA_PC)
--          at - 15:33:26 02/26/2017
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ENTITY AES_Dec_main_contrl IS
   PORT( 
      Data_rdy    : IN     std_logic;
      En_data     : IN     std_logic;
      Key_rdy     : IN     std_logic;
      clk         : IN     std_logic;
      rst         : IN     std_logic;
      En_data_reg : OUT    std_logic
   );

-- Declarations

END AES_Dec_main_contrl ;

-- hds interface_end
--
-- VHDL Architecture AES_Sound_1.AES_Dec_main_contrl.fsm
--
-- Created:
--          by - Mostafa.UNKNOWN (MOSTAFA_PC)
--          at - 15:33:26 02/26/2017
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE fsm OF AES_Dec_main_contrl IS

   -- Architecture Declarations
   TYPE STATE_TYPE IS (
      s5,
      s4,
      s0,
      s3,
      s1
   );

   -- State vector declaration
   ATTRIBUTE state_vector : string;
   ATTRIBUTE state_vector OF fsm : ARCHITECTURE IS "current_state" ;


   -- Declare current and next state signals
   SIGNAL current_state : STATE_TYPE ;
   SIGNAL next_state : STATE_TYPE ;

BEGIN

   ----------------------------------------------------------------------------
   clocked : PROCESS(
      clk,
      rst
   )
   ----------------------------------------------------------------------------
   BEGIN
      IF (rst = '0') THEN
         current_state <= s0;
         -- Reset Values
      ELSIF (rising_edge(clk)) THEN
         current_state <= next_state;
         -- Default Assignment To Internals

      END IF;

   END PROCESS clocked;

   ----------------------------------------------------------------------------
   nextstate : PROCESS (
      Data_rdy,
      En_data,
      Key_rdy,
      current_state
   )
   ----------------------------------------------------------------------------
   BEGIN
      CASE current_state IS
      WHEN s5 =>
         IF (Data_rdy = '1') THEN
            next_state <= s1;
         ELSE
            next_state <= s5;
         END IF;
      WHEN s4 =>
            next_state <= s5;
      WHEN s0 =>
         IF (Key_rdy = '1') THEN
            next_state <= s1;
         ELSE
            next_state <= s0;
         END IF;
      WHEN s3 =>
            next_state <= s4;
      WHEN s1 =>
         IF (En_data = '1') THEN
            next_state <= s3;
         ELSE
            next_state <= s1;
         END IF;
      WHEN OTHERS =>
         next_state <= s0;
      END CASE;

   END PROCESS nextstate;

   ----------------------------------------------------------------------------
   output : PROCESS (
      current_state
   )
   ----------------------------------------------------------------------------
   BEGIN
      -- Default Assignment
      En_data_reg <= '0';
      -- Default Assignment To Internals

      -- Combined Actions
      CASE current_state IS
      WHEN s4 =>
         En_data_reg <= '1';
      WHEN OTHERS =>
         NULL;
      END CASE;

   END PROCESS output;

   -- Concurrent Statements

END fsm;
