-- hds header_start
--
-- VHDL Entity AES_Sound_1.AES_combining.symbol
--
-- Created:
--          by - Mostafa.UNKNOWN (MOSTAFA_PC)
--          at - 15:33:26 02/26/2017
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ENTITY AES_combining IS
   PORT( 
      EN_Dec          : IN     std_logic;
      EN_Enc          : IN     std_logic;
      En_key          : IN     std_logic;
      In_Plain_Data   : IN     std_logic_vector (0 TO 127);
      clk             : IN     std_logic;
      in_Cipher_Data  : IN     std_logic_vector (0 TO 135);
      rst             : IN     std_logic;
      Chipher_D_Rdy   : OUT    std_logic;
      Out_Cipher_Data : OUT    std_logic_vector (0 TO 135);
      Out_Plain_Data  : OUT    std_logic_vector (0 TO 127);
      Plain_D_Rdy     : OUT    std_logic;
      key_rdy         : OUT    std_logic
   );

-- Declarations

END AES_combining ;

-- hds interface_end
--
-- VHDL Architecture AES_Sound_1.AES_combining.struct
--
-- Created:
--          by - Mostafa.UNKNOWN (MOSTAFA_PC)
--          at - 15:33:26 02/26/2017
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ARCHITECTURE struct OF AES_combining IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL in_127        : std_logic_vector(0 TO 127);
   SIGNAL in_128        : std_logic_vector(0 TO 127);
   SIGNAL rand_gen_seed : std_logic_vector(0 TO 7);
   SIGNAL s             : std_logic_vector(0 TO 7);


   -- Component Declarations
   COMPONENT Controlled_Top_AES
   PORT (
      Dec_seed_gen    : IN     std_logic_vector (0 TO 7);
      EN_Dec          : IN     std_logic ;
      EN_Enc          : IN     std_logic ;
      En_key          : IN     std_logic ;
      In_Plain_Data   : IN     std_logic_vector (0 TO 127);
      clk             : IN     std_logic ;
      in_Cipher_Data  : IN     std_logic_vector (0 TO 127);
      rst             : IN     std_logic ;
      Chipher_D_Rdy   : OUT    std_logic ;
      Out_Cipher_Data : OUT    std_logic_vector (0 TO 127);
      Out_Plain_Data  : OUT    std_logic_vector (0 TO 127);
      Plain_D_Rdy     : OUT    std_logic ;
      key_rdy         : OUT    std_logic ;
      rand_gen_seed   : OUT    std_logic_vector (0 TO 7)
   );
   END COMPONENT;
   COMPONENT interleaving_inv_sch
   PORT (
      com_out : IN     std_logic_vector (0 TO 135);
      in_127  : OUT    std_logic_vector (0 TO 127);
      s       : OUT    std_logic_vector (0 TO 7)
   );
   END COMPONENT;
   COMPONENT interleaving_sch
   PORT (
      in_127  : IN     std_logic_vector (0 TO 127);
      s       : IN     std_logic_vector (0 TO 7);
      com_out : OUT    std_logic_vector (0 TO 135)
   );
   END COMPONENT;



BEGIN
   -- Instance port mappings.
   I0 : Controlled_Top_AES
      PORT MAP (
         Dec_seed_gen    => s,
         EN_Dec          => EN_Dec,
         EN_Enc          => EN_Enc,
         En_key          => En_key,
         In_Plain_Data   => In_Plain_Data,
         clk             => clk,
         in_Cipher_Data  => in_128,
         rst             => rst,
         Chipher_D_Rdy   => Chipher_D_Rdy,
         Out_Cipher_Data => in_127,
         Out_Plain_Data  => Out_Plain_Data,
         Plain_D_Rdy     => Plain_D_Rdy,
         key_rdy         => key_rdy,
         rand_gen_seed   => rand_gen_seed
      );
   I1 : interleaving_inv_sch
      PORT MAP (
         com_out => in_Cipher_Data,
         in_127  => in_128,
         s       => s
      );
   I2 : interleaving_sch
      PORT MAP (
         in_127  => in_127,
         s       => rand_gen_seed,
         com_out => Out_Cipher_Data
      );

END struct;
