-- hds header_start
--
-- VHDL Entity AES_Sound_1.Enc_Ctrl.symbol
--
-- Created:
--          by - Mostafa.UNKNOWN (MOSTAFA_PC)
--          at - 15:33:14 02/26/2017
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ENTITY Enc_Ctrl IS
   PORT( 
      En       : IN     std_logic;
      clk      : IN     std_logic;
      rst      : IN     std_logic;
      Add      : OUT    std_logic_vector (0 TO 3);
      End_Enc  : OUT    std_logic;
      Last_RND : OUT    std_logic;
      Rnd_9    : OUT    std_logic
   );

-- Declarations

END Enc_Ctrl ;

-- hds interface_end
--
-- VHDL Architecture AES_Sound_1.Enc_Ctrl.fsm
--
-- Created:
--          by - Mostafa.UNKNOWN (MOSTAFA_PC)
--          at - 15:33:14 02/26/2017
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE fsm OF Enc_Ctrl IS

   -- Architecture Declarations
   TYPE STATE_TYPE IS (
      s0,
      s2,
      s3,
      s4,
      s5,
      s6,
      s7,
      s8,
      s9,
      s10,
      s1,
      s11
   );

   -- State vector declaration
   ATTRIBUTE state_vector : string;
   ATTRIBUTE state_vector OF fsm : ARCHITECTURE IS "current_state" ;


   -- Declare current and next state signals
   SIGNAL current_state : STATE_TYPE ;
   SIGNAL next_state : STATE_TYPE ;

BEGIN

   ----------------------------------------------------------------------------
   clocked : PROCESS(
      clk,
      rst
   )
   ----------------------------------------------------------------------------
   BEGIN
      IF (rst = '0') THEN
         current_state <= s0;
         -- Reset Values
      ELSIF (rising_edge(clk)) THEN
         current_state <= next_state;
         -- Default Assignment To Internals

      END IF;

   END PROCESS clocked;

   ----------------------------------------------------------------------------
   nextstate : PROCESS (
      En,
      current_state
   )
   ----------------------------------------------------------------------------
   BEGIN
      CASE current_state IS
      WHEN s0 =>
            next_state <= s2;
      WHEN s2 =>
         IF (En = '1') THEN
            next_state <= s3;
         ELSE
            next_state <= s2;
         END IF;
      WHEN s3 =>
            next_state <= s4;
      WHEN s4 =>
            next_state <= s5;
      WHEN s5 =>
            next_state <= s6;
      WHEN s6 =>
            next_state <= s7;
      WHEN s7 =>
            next_state <= s8;
      WHEN s8 =>
            next_state <= s9;
      WHEN s9 =>
            next_state <= s10;
      WHEN s10 =>
            next_state <= s1;
      WHEN s1 =>
            next_state <= s11;
      WHEN s11 =>
         IF (En = '1') THEN
            next_state <= s3;
         ELSE
            next_state <= s11;
         END IF;
      WHEN OTHERS =>
         next_state <= s0;
      END CASE;

   END PROCESS nextstate;

   ----------------------------------------------------------------------------
   output : PROCESS (
      current_state
   )
   ----------------------------------------------------------------------------
   BEGIN
      -- Default Assignment
      Add <= "0000";
      End_Enc <= '0';
      Last_RND <= '0';
      Rnd_9 <= '0';
      -- Default Assignment To Internals

      -- Combined Actions
      CASE current_state IS
      WHEN s2 =>
         add <= "0001";
      WHEN s3 =>
         add <= "0010";
      WHEN s4 =>
         add <= "0011";
      WHEN s5 =>
         add <= "0100";
      WHEN s6 =>
         add <= "0101";
      WHEN s7 =>
         add <= "0110";
      WHEN s8 =>
         add <= "0111";
      WHEN s9 =>
         add <= "1000";
      WHEN s10 =>
         add <= "1001";
      WHEN s1 =>
         Add <= "1010";
         Rnd_9 <= '1';
      WHEN s11 =>
         End_Enc <= '1';
         Add <="0001";
         Last_RND <= '1';
      WHEN OTHERS =>
         NULL;
      END CASE;

   END PROCESS output;

   -- Concurrent Statements

END fsm;
