-- hds header_start
--
-- VHDL Entity AES_Sound_1.interleaving_inv_sch.symbol
--
-- Created:
--          by - Mostafa.UNKNOWN (MOSTAFA_PC)
--          at - 15:33:13 02/26/2017
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ENTITY interleaving_inv_sch IS
   PORT( 
      com_out : IN     std_logic_vector (0 TO 135);
      in_127  : OUT    std_logic_vector (0 TO 127);
      s       : OUT    std_logic_vector (0 TO 7)
   );

-- Declarations

END interleaving_inv_sch ;

-- hds interface_end
--
-- VHDL Architecture AES_Sound_1.interleaving_inv_sch.struct
--
-- Created:
--          by - Mostafa.UNKNOWN (MOSTAFA_PC)
--          at - 15:33:14 02/26/2017
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;



ARCHITECTURE struct OF interleaving_inv_sch IS

   -- Architecture declarations

   -- Internal signal declarations



BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 2 eb2
   in_127(0 to 12) <= com_out(0 to 12) ;
   s(0) <= com_out(13) ;
   in_127(13 to 24) <= com_out(14 to 25) ;
   s(1) <= com_out(26);
   in_127(25 to 30) <= com_out(27 to 32);
   s(2) <= com_out(33);
   in_127(31 to 46) <= com_out(34 to 49);
   s(3) <= com_out(50);
   in_127(47 to 85) <= com_out(51 to 89);
   s(4) <= com_out(90);
   in_127(86 to 104) <= com_out(91 to 109);
   s(5) <= com_out(110);
   in_127(105 to 120) <= com_out(111 to 126);
   s(6) <= com_out(127);
   in_127(121 to 127) <= com_out(128 to 134);
   s(7) <= com_out(135);

   -- Instance port mappings.

END struct;
