-- hds header_start
--
-- VHDL Entity AES_Sound_1.Key_Sbox_Rotat.symbol
--
-- Created:
--          by - Mostafa.UNKNOWN (MOSTAFA_PC)
--          at - 15:33:20 02/26/2017
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ENTITY Key_Sbox_Rotat IS
   PORT( 
      En_rcon  : IN     std_logic;
      clk      : IN     std_logic;
      rom_in1  : IN     std_logic_vector (0 TO 7);
      rom_in2  : IN     std_logic_vector (0 TO 7);
      rom_in3  : IN     std_logic_vector (0 TO 7);
      rom_in4  : IN     std_logic_vector (0 TO 7);
      rst      : IN     std_logic;
      rom_out1 : OUT    std_logic_vector (0 TO 7);
      rom_out2 : OUT    std_logic_vector (0 TO 7);
      rom_out3 : OUT    std_logic_vector (0 TO 7);
      rom_out4 : OUT    std_logic_vector (0 TO 7)
   );

-- Declarations

END Key_Sbox_Rotat ;

-- hds interface_end
--
-- VHDL Architecture AES_Sound_1.Key_Sbox_Rotat.struct
--
-- Created:
--          by - Mostafa.UNKNOWN (MOSTAFA_PC)
--          at - 15:33:20 02/26/2017
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF Key_Sbox_Rotat IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL R_Con   : std_logic_vector(0 TO 7);
   SIGNAL rom_out : std_logic_vector(0 TO 7);


   -- Component Declarations
   COMPONENT Round_constant_ctrl
   PORT (
      En    : IN     std_logic ;
      clk   : IN     std_logic ;
      rst   : IN     std_logic ;
      R_Con : OUT    std_logic_vector (0 TO 7)
   );
   END COMPONENT;
   COMPONENT Xor8bit
   PORT (
      in0  : IN     std_logic_vector (0 TO 7);
      in1  : IN     std_logic_vector (0 TO 7);
      out0 : OUT    std_logic_vector (0 TO 7)
   );
   END COMPONENT;
   COMPONENT sbox_rom
   PORT (
      rom_in  : IN     std_logic_vector (0 TO 7);
      clk     : IN     std_logic ;
      rom_out : OUT    std_logic_vector (0 TO 7)
   );
   END COMPONENT;



BEGIN
   -- Instance port mappings.
   I5 : Round_constant_ctrl
      PORT MAP (
         En    => En_rcon,
         clk   => clk,
         rst   => rst,
         R_Con => R_Con
      );
   I4 : Xor8bit
      PORT MAP (
         in0  => R_Con,
         in1  => rom_out,
         out0 => rom_out1
      );
   I0 : sbox_rom
      PORT MAP (
         rom_in  => rom_in2,
         clk     => clk,
         rom_out => rom_out
      );
   I1 : sbox_rom
      PORT MAP (
         rom_in  => rom_in3,
         clk     => clk,
         rom_out => rom_out2
      );
   I2 : sbox_rom
      PORT MAP (
         rom_in  => rom_in4,
         clk     => clk,
         rom_out => rom_out3
      );
   I3 : sbox_rom
      PORT MAP (
         rom_in  => rom_in1,
         clk     => clk,
         rom_out => rom_out4
      );

END struct;
