-- hds header_start
--
-- VHDL Architecture Sbox_Mathematical_Module.Ram_256.rtl
--
-- Created:
--          by - XPPRESP3.UNKNOWN (USER)
--          at - 21:53:13 01/16/2009
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
USE ieee.std_logic_unsigned.all;


ENTITY key_Ram IS
   PORT( 
      add      : IN     std_logic_vector (0 TO 3);
      clk      : IN     std_logic;
      data_in  : IN     std_logic_vector (0 TO 127);
      w_en     : IN     std_logic;
      data_out : OUT    std_logic_vector (0 TO 127)
   );

-- Declarations

END key_Ram ;

-- hds interface_end
ARCHITECTURE rtl OF key_Ram IS
type Mem is array(0 to 10) of std_logic_vector(0 to 127);
signal mem_signal : mem;
BEGIN
process(clk,data_in,w_en,add)--parameter list and this code is synthizable by the tool as memory element 
variable add_temp : std_logic_vector(0 to 3);
begin 
	add_temp := add;
	if(rising_edge(clk)) then
		if(w_en = '1') then
		mem_signal(conv_integer(add_temp)) <= data_in;
		end if;
		data_out <= mem_signal(conv_integer(add_temp));
	end if;
end process;
END rtl;
