-- hds header_start
--
-- VHDL Architecture Mostafa_AES.M_Selector.rtl
--
-- Created:
--          by - Mostafa_Ahmed.UNKNOWN (MOSTAFA)
--          at - 10:41:09 01/11/2009
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ENTITY M_Selector IS
   PORT( 
      Internal1 : IN     std_logic_vector (0 TO 7);
      Internal2 : IN     std_logic_vector (0 TO 7);
      Internal3 : IN     std_logic_vector (0 TO 7);
      Internal4 : IN     std_logic_vector (0 TO 7);
      Internal5 : IN     std_logic_vector (0 TO 7);
      Internal6 : IN     std_logic_vector (0 TO 7);
      Internal7 : IN     std_logic_vector (0 TO 7);
      Internal8 : IN     std_logic_vector (0 TO 7);
      M_OUT     : OUT    std_logic_vector (0 TO 7)
   );

-- Declarations

END M_Selector ;

-- hds interface_end
ARCHITECTURE rtl OF M_Selector IS
BEGIN
M_OUT <= Internal1 xor Internal2 xor Internal3 xor Internal4 xor Internal5 xor Internal6 xor Internal7 xor Internal8;
END rtl;
