-- hds header_start
--
-- VHDL Architecture AES_Algorithm.MCol_Left_Shift.rtl
--
-- Created:
--          by - Administrator.UNKNOWN (PC2)
--          at - 22:32:14 19/11/2005
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ENTITY MCol_Left_Shift IS
   PORT( 
      lshiftip : IN     std_logic_vector (0 TO 7);
      lshiftop : OUT    std_logic_vector (0 TO 7)
   );

-- Declarations

END MCol_Left_Shift ;

-- hds interface_end
ARCHITECTURE Left_Shift OF MCol_Left_Shift IS
BEGIN
	LShiftOP<=  ((LshiftIP(1 to 7) & '0') Xor "00011011") when LshiftIP(0)='1' else
				(LshiftIP(1 to 7) & '0');
END Left_Shift;
