-- hds header_start
--
-- VHDL Entity AES_Sound_1.MIxCol_one.symbol
--
-- Created:
--          by - Mostafa.UNKNOWN (MOSTAFA_PC)
--          at - 15:33:16 02/26/2017
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ENTITY MIxCol_one IS
   PORT( 
      Multiplicand  : IN     std_logic_vector (0 TO 7);
      Multiplicand1 : IN     std_logic_vector (0 TO 7);
      Multiplicand2 : IN     std_logic_vector (0 TO 7);
      Multiplicand3 : IN     std_logic_vector (0 TO 7);
      Multplier     : IN     std_logic_vector (0 TO 7);
      Multplier1    : IN     std_logic_vector (0 TO 7);
      Multplier2    : IN     std_logic_vector (0 TO 7);
      Multplier3    : IN     std_logic_vector (0 TO 7);
      xorop         : OUT    std_logic_vector (0 TO 7)
   );

-- Declarations

END MIxCol_one ;

-- hds interface_end
--
-- VHDL Architecture AES_Sound_1.MIxCol_one.struct
--
-- Created:
--          by - Mostafa.UNKNOWN (MOSTAFA_PC)
--          at - 15:33:16 02/26/2017
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF MIxCol_one IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL M_OUT  : std_logic_vector(0 TO 7);
   SIGNAL M_OUT1 : std_logic_vector(0 TO 7);
   SIGNAL M_OUT2 : std_logic_vector(0 TO 7);
   SIGNAL M_OUT3 : std_logic_vector(0 TO 7);


   -- Component Declarations
   COMPONENT Multiplier_GF
   PORT (
      Multiplicand : IN     std_logic_vector (0 TO 7);
      Multplier    : IN     std_logic_vector (0 TO 7);
      M_OUT        : OUT    std_logic_vector (0 TO 7)
   );
   END COMPONENT;
   COMPONENT Xor_4Byte
   PORT (
      ip1   : IN     std_logic_vector (0 TO 7);
      ip2   : IN     std_logic_vector (0 TO 7);
      ip3   : IN     std_logic_vector (0 TO 7);
      ip4   : IN     std_logic_vector (0 TO 7);
      xorop : OUT    std_logic_vector (0 TO 7)
   );
   END COMPONENT;

BEGIN
   -- Instance port mappings.
   I0 : Multiplier_GF
      PORT MAP (
         Multiplicand => Multiplicand,
         Multplier    => Multplier,
         M_OUT        => M_OUT
      );
   I1 : Multiplier_GF
      PORT MAP (
         Multiplicand => Multiplicand1,
         Multplier    => Multplier1,
         M_OUT        => M_OUT1
      );
   I2 : Multiplier_GF
      PORT MAP (
         Multiplicand => Multiplicand2,
         Multplier    => Multplier2,
         M_OUT        => M_OUT2
      );
   I3 : Multiplier_GF
      PORT MAP (
         Multiplicand => Multiplicand3,
         Multplier    => Multplier3,
         M_OUT        => M_OUT3
      );
   I4 : Xor_4Byte
      PORT MAP (
         ip1   => M_OUT,
         ip2   => M_OUT1,
         ip3   => M_OUT2,
         ip4   => M_OUT3,
         xorop => xorop
      );

END struct;
