-- hds header_start
--
-- VHDL Architecture Reconfigurable_AES.Mux2_1.untitled
--
-- Created:
--          by - mostafa_ahmed.UNKNOWN (MOSTAFA)
--          at - 20:54:50 02/27/2009
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ENTITY Mux2_1 IS
   PORT( 
      In0  : IN     std_logic_vector (0 TO 127);
      In1  : IN     std_logic_vector (0 TO 127);
      sel  : IN     std_logic;
      out0 : OUT    std_logic_vector (0 TO 127)
   );

-- Declarations

END Mux2_1 ;

-- hds interface_end
ARCHITECTURE untitled OF Mux2_1 IS
BEGIN
out0 <= in0 when sel = '1' else in1;
END untitled;
