-- hds header_start
--
-- VHDL Architecture Reconfigurable_AES.Mux_add.rtl
--
-- Created:
--          by - mostafa_ahmed.UNKNOWN (MOSTAFA)
--          at - 13:52:01 03/01/2010
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ENTITY Mux_add IS
   PORT( 
      In0  : IN     std_logic_vector (0 TO 3);
      In1  : IN     std_logic_vector (0 TO 3);
      sel  : IN     std_logic;
      Out0 : OUT    std_logic_vector (0 TO 3)
   );

-- Declarations

END Mux_add ;

-- hds interface_end
ARCHITECTURE rtl OF Mux_add IS
BEGIN
out0 <= in0 when sel = '1' else in1;
END rtl;
