-- hds header_start
--
-- VHDL Architecture Reconfigurable_AES.Mux_16_1.rtl
--
-- Created:
--          by - Mostafa_Ahmed.UNKNOWN (MOSTAFA)
--          at - 12:06:31 02/24/2010
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ENTITY Mux_16_1 IS
   PORT( 
      In1      : IN     std_logic_vector (0 TO 7);
      In10     : IN     std_logic_vector (0 TO 7);
      In11     : IN     std_logic_vector (0 TO 7);
      In12     : IN     std_logic_vector (0 TO 7);
      In13     : IN     std_logic_vector (0 TO 7);
      In14     : IN     std_logic_vector (0 TO 7);
      In15     : IN     std_logic_vector (0 TO 7);
      In16     : IN     std_logic_vector (0 TO 7);
      In2      : IN     std_logic_vector (0 TO 7);
      In3      : IN     std_logic_vector (0 TO 7);
      In4      : IN     std_logic_vector (0 TO 7);
      In5      : IN     std_logic_vector (0 TO 7);
      In6      : IN     std_logic_vector (0 TO 7);
      In7      : IN     std_logic_vector (0 TO 7);
      In8      : IN     std_logic_vector (0 TO 7);
      In9      : IN     std_logic_vector (0 TO 7);
      Sel      : IN     std_logic_vector (0 TO 3);
      shit_out : OUT    std_logic_vector (0 TO 7)
   );

-- Declarations

END Mux_16_1 ;

-- hds interface_end
ARCHITECTURE rtl OF Mux_16_1 IS
BEGIN
shit_out <= in16 when sel = "1111" else
			in15 when sel = "1110" else
			in14 when sel = "1101" else
			in13 when sel = "1100" else
			in12 when sel = "1011" else
			in11 when sel = "1010" else
			in10 when sel = "1001" else
			in9 when sel = "1000" else
			in8 when sel = "0111" else
			in7 when sel = "0110" else
			in6 when sel = "0101" else
			in5 when sel = "0100" else
			in4 when sel = "0011" else
			in3 when sel = "0010" else
			in2 when sel = "0001" else
			in1 when sel = "0000" else
			"00000000";
END rtl;
