-- hds header_start
--
-- VHDL Architecture ReconFig_Aes.Mux_32.rtl
--
-- Created:
--          by - mostafa_ahmed.UNKNOWN (MOSTAFA)
--          at - 21:10:48 03/03/2010
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ENTITY Mux_32 IS
   PORT( 
      In0  : IN     std_logic_vector (0 TO 31);
      In1  : IN     std_logic_vector (0 TO 31);
      Sel  : IN     std_logic;
      out0 : OUT    std_logic_vector (0 TO 31)
   );

-- Declarations

END Mux_32 ;

-- hds interface_end
ARCHITECTURE rtl OF Mux_32 IS
BEGIN
out0 <= in0 when sel = '1' else in1;
END rtl;
