-- hds header_start
--
-- VHDL Architecture Mostafa_AES.Mux_2x1.rtl
--
-- Created:
--          by - Mostafa_Ahmed.UNKNOWN (MOSTAFA)
--          at - 11:05:31 01/11/2009
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ENTITY Mux_Sel_GND IS
   PORT( 
      In0  : IN     std_logic_vector (0 TO 7);
      Sel  : IN     std_logic;
      Out0 : OUT    std_logic_vector (0 TO 7)
   );

-- Declarations

END Mux_Sel_GND ;

-- hds interface_end
ARCHITECTURE rtl OF Mux_Sel_GND IS
BEGIN
Out0 <= in0 when sel = '1' else
"00000000";
END rtl;
