-- hds header_start
--
-- VHDL Architecture AES_RECONFIG.REG8.rtl
--
-- Created:
--          by - Mostafa_Ahmed.UNKNOWN (MOSTAFA)
--          at - 11:35:51 04/06/2010
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ENTITY REG8 IS
   PORT( 
      clk  : IN     std_logic;
      en   : IN     std_logic;
      in0  : IN     std_logic_vector (0 TO 7);
      rst  : IN     std_logic;
      out0 : OUT    std_logic_vector (0 TO 7)
   );

-- Declarations

END REG8 ;

-- hds interface_end
ARCHITECTURE rtl OF REG8 IS
signal temp :std_logic_vector(0 to 7); 
BEGIN
process(clk,rst,en,in0)
begin
if(rst='0')then
temp <= (others=>'0');
elsif(rising_edge(clk))then
if(en = '1')then
temp <=in0;
end if;
end if;
end process;
out0<= temp;
END rtl;
