-- hds header_start
--
-- VHDL Architecture Reconfigurable_AES.REG_32.untitled
--
-- Created:
--          by - mostafa_ahmed.UNKNOWN (MOSTAFA)
--          at - 23:15:18 02/28/2010
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ENTITY REG_32 IS
   PORT( 
      Clk  : IN     std_logic;
      En   : IN     std_logic;
      In0  : IN     std_logic_vector (0 TO 31);
      rst  : IN     std_logic;
      out0 : OUT    std_logic_vector (0 TO 31)
   );

-- Declarations

END REG_32 ;

-- hds interface_end
ARCHITECTURE untitled OF REG_32 IS
signal temp :std_logic_vector(0 to 31); 
BEGIN
process(clk,rst,en,in0)
begin
if(rst='0')then
temp <= (others=>'0');
elsif(rising_edge(clk))then
if(en = '1')then
temp <=in0;
end if;
end if;
end process;
out0<= temp;
END untitled;
