-- hds header_start
--
-- VHDL Entity AES_Sound_1.Shit_w.symbol
--
-- Created:
--          by - Mostafa.UNKNOWN (MOSTAFA_PC)
--          at - 15:33:14 02/26/2017
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ENTITY Shit_w IS
   PORT( 
      in1       : IN     std_logic_vector (0 TO 7);
      in10      : IN     std_logic_vector (0 TO 7);
      in11      : IN     std_logic_vector (0 TO 7);
      in12      : IN     std_logic_vector (0 TO 7);
      in13      : IN     std_logic_vector (0 TO 7);
      in14      : IN     std_logic_vector (0 TO 7);
      in15      : IN     std_logic_vector (0 TO 7);
      in16      : IN     std_logic_vector (0 TO 7);
      in2       : IN     std_logic_vector (0 TO 7);
      in3       : IN     std_logic_vector (0 TO 7);
      in4       : IN     std_logic_vector (0 TO 7);
      in5       : IN     std_logic_vector (0 TO 7);
      in6       : IN     std_logic_vector (0 TO 7);
      in7       : IN     std_logic_vector (0 TO 7);
      in8       : IN     std_logic_vector (0 TO 7);
      in9       : IN     std_logic_vector (0 TO 7);
      sel1      : IN     std_logic_vector (0 TO 3);
      sel2      : IN     std_logic_vector (0 TO 3);
      sel3      : IN     std_logic_vector (0 TO 3);
      sel4      : IN     std_logic_vector (0 TO 3);
      shit_out1 : OUT    std_logic_vector (0 TO 7);
      shit_out2 : OUT    std_logic_vector (0 TO 7);
      shit_out3 : OUT    std_logic_vector (0 TO 7);
      shit_out4 : OUT    std_logic_vector (0 TO 7)
   );

-- Declarations

END Shit_w ;

-- hds interface_end
--
-- VHDL Architecture AES_Sound_1.Shit_w.struct
--
-- Created:
--          by - Mostafa.UNKNOWN (MOSTAFA_PC)
--          at - 15:33:15 02/26/2017
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF Shit_w IS

   -- Architecture declarations

   -- Internal signal declarations


   -- Component Declarations
   COMPONENT Mux_16_1
   PORT (
      in1      : IN     std_logic_vector (0 TO 7);
      in10     : IN     std_logic_vector (0 TO 7);
      in11     : IN     std_logic_vector (0 TO 7);
      in12     : IN     std_logic_vector (0 TO 7);
      in13     : IN     std_logic_vector (0 TO 7);
      in14     : IN     std_logic_vector (0 TO 7);
      in15     : IN     std_logic_vector (0 TO 7);
      in16     : IN     std_logic_vector (0 TO 7);
      in2      : IN     std_logic_vector (0 TO 7);
      in3      : IN     std_logic_vector (0 TO 7);
      in4      : IN     std_logic_vector (0 TO 7);
      in5      : IN     std_logic_vector (0 TO 7);
      in6      : IN     std_logic_vector (0 TO 7);
      in7      : IN     std_logic_vector (0 TO 7);
      in8      : IN     std_logic_vector (0 TO 7);
      in9      : IN     std_logic_vector (0 TO 7);
      sel      : IN     std_logic_vector (0 TO 3);
      shit_out : OUT    std_logic_vector (0 TO 7)
   );
   END COMPONENT;

BEGIN
   -- Instance port mappings.
   I0 : Mux_16_1
      PORT MAP (
         in1      => in1,
         in10     => in10,
         in11     => in11,
         in12     => in12,
         in13     => in13,
         in14     => in14,
         in15     => in15,
         in16     => in16,
         in2      => in2,
         in3      => in3,
         in4      => in4,
         in5      => in5,
         in6      => in6,
         in7      => in7,
         in8      => in8,
         in9      => in9,
         sel      => sel1,
         shit_out => shit_out1
      );
   I1 : Mux_16_1
      PORT MAP (
         in1      => in1,
         in10     => in10,
         in11     => in11,
         in12     => in12,
         in13     => in13,
         in14     => in14,
         in15     => in15,
         in16     => in16,
         in2      => in2,
         in3      => in3,
         in4      => in4,
         in5      => in5,
         in6      => in6,
         in7      => in7,
         in8      => in8,
         in9      => in9,
         sel      => sel2,
         shit_out => shit_out2
      );
   I2 : Mux_16_1
      PORT MAP (
         in1      => in1,
         in10     => in10,
         in11     => in11,
         in12     => in12,
         in13     => in13,
         in14     => in14,
         in15     => in15,
         in16     => in16,
         in2      => in2,
         in3      => in3,
         in4      => in4,
         in5      => in5,
         in6      => in6,
         in7      => in7,
         in8      => in8,
         in9      => in9,
         sel      => sel3,
         shit_out => shit_out3
      );
   I3 : Mux_16_1
      PORT MAP (
         in1      => in1,
         in10     => in10,
         in11     => in11,
         in12     => in12,
         in13     => in13,
         in14     => in14,
         in15     => in15,
         in16     => in16,
         in2      => in2,
         in3      => in3,
         in4      => in4,
         in5      => in5,
         in6      => in6,
         in7      => in7,
         in8      => in8,
         in9      => in9,
         sel      => sel4,
         shit_out => shit_out4
      );

END struct;
