-- hds header_start
--
-- VHDL Entity AES_Sound_1.Top_MIxCol.symbol
--
-- Created:
--          by - Mostafa.UNKNOWN (MOSTAFA_PC)
--          at - 15:33:16 02/26/2017
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ENTITY Top_MIxCol IS
   PORT( 
      Data1      : IN     std_logic_vector (0 TO 7);
      Data10     : IN     std_logic_vector (0 TO 7);
      Data11     : IN     std_logic_vector (0 TO 7);
      Data12     : IN     std_logic_vector (0 TO 7);
      Data13     : IN     std_logic_vector (0 TO 7);
      Data14     : IN     std_logic_vector (0 TO 7);
      Data15     : IN     std_logic_vector (0 TO 7);
      Data16     : IN     std_logic_vector (0 TO 7);
      Data2      : IN     std_logic_vector (0 TO 7);
      Data3      : IN     std_logic_vector (0 TO 7);
      Data4      : IN     std_logic_vector (0 TO 7);
      Data5      : IN     std_logic_vector (0 TO 7);
      Data6      : IN     std_logic_vector (0 TO 7);
      Data7      : IN     std_logic_vector (0 TO 7);
      Data8      : IN     std_logic_vector (0 TO 7);
      Data9      : IN     std_logic_vector (0 TO 7);
      Mult1      : IN     std_logic_vector (0 TO 7);
      Mult2      : IN     std_logic_vector (0 TO 7);
      Mult3      : IN     std_logic_vector (0 TO 7);
      Mult4      : IN     std_logic_vector (0 TO 7);
      word_out1  : OUT    std_logic_vector (0 TO 7);
      word_out10 : OUT    std_logic_vector (0 TO 7);
      word_out11 : OUT    std_logic_vector (0 TO 7);
      word_out12 : OUT    std_logic_vector (0 TO 7);
      word_out13 : OUT    std_logic_vector (0 TO 7);
      word_out14 : OUT    std_logic_vector (0 TO 7);
      word_out15 : OUT    std_logic_vector (0 TO 7);
      word_out16 : OUT    std_logic_vector (0 TO 7);
      word_out2  : OUT    std_logic_vector (0 TO 7);
      word_out3  : OUT    std_logic_vector (0 TO 7);
      word_out4  : OUT    std_logic_vector (0 TO 7);
      word_out5  : OUT    std_logic_vector (0 TO 7);
      word_out6  : OUT    std_logic_vector (0 TO 7);
      word_out7  : OUT    std_logic_vector (0 TO 7);
      word_out8  : OUT    std_logic_vector (0 TO 7);
      word_out9  : OUT    std_logic_vector (0 TO 7)
   );

-- Declarations

END Top_MIxCol ;

-- hds interface_end
--
-- VHDL Architecture AES_Sound_1.Top_MIxCol.struct
--
-- Created:
--          by - Mostafa.UNKNOWN (MOSTAFA_PC)
--          at - 15:33:16 02/26/2017
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF Top_MIxCol IS

   -- Architecture declarations

   -- Internal signal declarations


   -- Component Declarations
   COMPONENT MixCol_word
   PORT (
      Data1     : IN     std_logic_vector (0 TO 7);
      Data2     : IN     std_logic_vector (0 TO 7);
      Data3     : IN     std_logic_vector (0 TO 7);
      Data4     : IN     std_logic_vector (0 TO 7);
      Mult1     : IN     std_logic_vector (0 TO 7);
      Mult2     : IN     std_logic_vector (0 TO 7);
      Mult3     : IN     std_logic_vector (0 TO 7);
      Mult4     : IN     std_logic_vector (0 TO 7);
      word_out1 : OUT    std_logic_vector (0 TO 7);
      word_out2 : OUT    std_logic_vector (0 TO 7);
      word_out3 : OUT    std_logic_vector (0 TO 7);
      word_out4 : OUT    std_logic_vector (0 TO 7)
   );
   END COMPONENT;

BEGIN
   -- Instance port mappings.
   I0 : MixCol_word
      PORT MAP (
         Data1     => Data1,
         Data2     => Data2,
         Data3     => Data3,
         Data4     => Data4,
         Mult1     => Mult1,
         Mult2     => Mult2,
         Mult3     => Mult3,
         Mult4     => Mult4,
         word_out1 => word_out1,
         word_out2 => word_out2,
         word_out3 => word_out3,
         word_out4 => word_out4
      );
   I1 : MixCol_word
      PORT MAP (
         Data1     => Data5,
         Data2     => Data6,
         Data3     => Data7,
         Data4     => Data8,
         Mult1     => Mult1,
         Mult2     => Mult2,
         Mult3     => Mult3,
         Mult4     => Mult4,
         word_out1 => word_out5,
         word_out2 => word_out6,
         word_out3 => word_out7,
         word_out4 => word_out8
      );
   I2 : MixCol_word
      PORT MAP (
         Data1     => Data9,
         Data2     => Data10,
         Data3     => Data11,
         Data4     => Data12,
         Mult1     => Mult1,
         Mult2     => Mult2,
         Mult3     => Mult3,
         Mult4     => Mult4,
         word_out1 => word_out9,
         word_out2 => word_out10,
         word_out3 => word_out11,
         word_out4 => word_out12
      );
   I3 : MixCol_word
      PORT MAP (
         Data1     => Data13,
         Data2     => Data14,
         Data3     => Data15,
         Data4     => Data16,
         Mult1     => Mult1,
         Mult2     => Mult2,
         Mult3     => Mult3,
         Mult4     => Mult4,
         word_out1 => word_out13,
         word_out2 => word_out14,
         word_out3 => word_out15,
         word_out4 => word_out16
      );

END struct;
