-- hds header_start
--
-- VHDL Entity AES_Sound_1.Top_Dec.symbol
--
-- Created:
--          by - Mostafa.UNKNOWN (MOSTAFA_PC)
--          at - 15:33:24 02/26/2017
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ENTITY Top_Dec IS
   PORT( 
      EN      : IN     std_logic;
      IN_Data : IN     std_logic_vector (0 TO 127);
      IN_Mult : IN     std_logic_vector (0 TO 31);
      IN_Sel  : IN     std_logic_vector (0 TO 63);
      Reg_Key : IN     std_logic_vector (0 TO 127);
      clk     : IN     std_logic;
      rst     : IN     std_logic;
      Add     : OUT    std_logic_vector (0 TO 3);
      End_Dec : OUT    std_logic;
      RND_OUT : OUT    std_logic_vector (0 TO 127);
      Rnd_9   : OUT    std_logic
   );

-- Declarations

END Top_Dec ;

-- hds interface_end
--
-- VHDL Architecture AES_Sound_1.Top_Dec.struct
--
-- Created:
--          by - Mostafa.UNKNOWN (MOSTAFA_PC)
--          at - 15:33:24 02/26/2017
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF Top_Dec IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL Last_RND : std_logic;
   SIGNAL out0     : std_logic_vector(0 TO 127);
   SIGNAL out2     : std_logic_vector(0 TO 31);
   SIGNAL out_reg1 : std_logic_vector(0 TO 31);

   -- Implicit buffer signal declarations
   SIGNAL RND_OUT_internal : std_logic_vector (0 TO 127);


   -- Component Declarations
   COMPONENT Enc_Ctrl
   PORT (
      En       : IN     std_logic ;
      clk      : IN     std_logic ;
      rst      : IN     std_logic ;
      Add      : OUT    std_logic_vector (0 TO 3);
      End_Enc  : OUT    std_logic ;
      Last_RND : OUT    std_logic ;
      Rnd_9    : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT Mux2_1
   PORT (
      in0  : IN     std_logic_vector (0 TO 127);
      in1  : IN     std_logic_vector (0 TO 127);
      sel  : IN     std_logic ;
      out0 : OUT    std_logic_vector (0 TO 127)
   );
   END COMPONENT;
   COMPONENT Mux_32
   PORT (
      in0  : IN     std_logic_vector (0 TO 31);
      in1  : IN     std_logic_vector (0 TO 31);
      sel  : IN     std_logic ;
      out0 : OUT    std_logic_vector (0 TO 31)
   );
   END COMPONENT;
   COMPONENT Reg_Mult_ini
   PORT (
      out_reg : OUT    std_logic_vector (0 TO 31)
   );
   END COMPONENT;
   COMPONENT Rnd_inv
   PORT (
      Key       : IN     std_logic_vector (0 TO 127);
      Mult      : IN     std_logic_vector (0 TO 31);
      RND_Input : IN     std_logic_vector (0 TO 127);
      Sel       : IN     std_logic_vector (0 TO 63);
      clk       : IN     std_logic ;
      RND_OUT   : OUT    std_logic_vector (0 TO 127)
   );
   END COMPONENT;


BEGIN
   -- Instance port mappings.
   I2 : Enc_Ctrl
      PORT MAP (
         En       => EN,
         clk      => clk,
         rst      => rst,
         Add      => Add,
         End_Enc  => End_Dec,
         Last_RND => Last_RND,
         Rnd_9    => Rnd_9
      );
   I3 : Mux2_1
      PORT MAP (
         in0  => IN_Data,
         in1  => RND_OUT_internal,
         sel  => EN,
         out0 => out0
      );
   I9 : Mux_32
      PORT MAP (
         In0  => out_reg1,
         In1  => IN_Mult,
         Sel  => Last_RND,
         out0 => out2
      );
   I7 : Reg_Mult_ini
      PORT MAP (
         out_reg => out_reg1
      );
   I1 : Rnd_inv
      PORT MAP (
         Key       => Reg_Key,
         Mult      => out2,
         RND_Input => out0,
         Sel       => IN_Sel,
         clk       => clk,
         RND_OUT   => RND_OUT_internal
      );

   -- Implicit buffered output assignments
   RND_OUT <= RND_OUT_internal;

END struct;
