-- hds header_start
--
-- VHDL Architecture AES_RECONFIG.Xor8bit.rtl
--
-- Created:
--          by - Mostafa_Ahmed.UNKNOWN (MOSTAFA)
--          at - 09:36:40 04/12/2010
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ENTITY Xor8bit IS
   PORT( 
      in0  : IN     std_logic_vector (0 TO 7);
      in1  : IN     std_logic_vector (0 TO 7);
      out0 : OUT    std_logic_vector (0 TO 7)
   );

-- Declarations

END Xor8bit ;

-- hds interface_end
ARCHITECTURE rtl OF Xor8bit IS
BEGIN
out0 <= in0 xor in1;
END rtl;
