-- hds header_start
--
-- VHDL Architecture ReconFig_Aes.Xor_128.rtl
--
-- Created:
--          by - mostafa_ahmed.UNKNOWN (MOSTAFA)
--          at - 20:04:45 03/03/2010
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ENTITY Xor_128 IS
   PORT( 
      In0  : IN     std_logic_vector (0 TO 127);
      In1  : IN     std_logic_vector (0 TO 127);
      Out0 : OUT    std_logic_vector (0 TO 127)
   );

-- Declarations

END Xor_128 ;

-- hds interface_end
ARCHITECTURE rtl OF Xor_128 IS
BEGIN
out0 <= in0 xor in1;
END rtl;
