-- hds header_start
--
-- VHDL Architecture ReconFig_Aes.xor_byte.rtl
--
-- Created:
--          by - USER.UNKNOWN (TECHNO-995171B5)
--          at - 15:27:30 03/03/2010
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ENTITY xor_byte IS
   PORT( 
      In0  : IN     std_logic_vector (0 TO 7);
      In1  : IN     std_logic_vector (0 TO 7);
      Out0 : OUT    std_logic_vector (0 TO 7)
   );

-- Declarations

END xor_byte ;

-- hds interface_end
ARCHITECTURE rtl OF xor_byte IS
BEGIN
out0 <= in0 xor in1;
END rtl;
