-- VHDL Entity my_project1_lib.dec_lib.symbol
--
-- Created:
--          by - Mostafa.UNKNOWN (MOSTAFA_PC)
--          at - 11:43:46 02/27/2017
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2007.1 (Build 19)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY dec_lib IS
   PORT( 
      chipherd_in   : IN     std_logic_vector ( 135 DOWNTO 0 );
      clk           : IN     std_logic;
      decipher_en   : IN     std_logic;
      from_aes      : IN     std_logic_vector ( 127 DOWNTO 0 );
      idec          : IN     std_logic;
      ienc          : IN     std_logic;
      intr_from_aes : IN     std_logic;
      ioff          : IN     std_logic;
      ion           : IN     std_logic;
      dec_a         : OUT    std_logic_vector (15 DOWNTO 0);
      dec_b         : OUT    std_logic_vector (15 DOWNTO 0);
      intr_to_aes   : OUT    std_logic;
      to_aes        : OUT    std_logic_vector ( 135 DOWNTO 0 )
   );

-- Declarations

END dec_lib ;

--
-- VHDL Architecture my_project1_lib.dec_lib.struct
--
-- Created:
--          by - Mostafa.UNKNOWN (MOSTAFA_PC)
--          at - 11:43:46 02/27/2017
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2007.1 (Build 19)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY my_project1_lib;

ARCHITECTURE struct OF dec_lib IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL load       : std_logic;
   SIGNAL reg_out    : std_logic_vector(127 DOWNTO 0);
   SIGNAL shift_intr : std_logic;


   -- Component Declarations
   COMPONENT dec_ctrl
   PORT (
      chipherd_in   : IN     std_logic_vector ( 135 DOWNTO 0 );
      clk           : IN     std_logic ;
      decipher_en   : IN     std_logic ;
      from_aes      : IN     std_logic_vector ( 127 DOWNTO 0 );
      idec          : IN     std_logic ;
      intr_from_aes : IN     std_logic ;
      ion           : IN     std_logic ;
      intr_to_aes   : OUT    std_logic ;
      load          : OUT    std_logic ;
      reg_out       : OUT    std_logic_vector (127 DOWNTO 0);
      shift_intr    : OUT    std_logic ;
      to_aes        : OUT    std_logic_vector ( 135 DOWNTO 0 )
   );
   END COMPONENT;
   COMPONENT reg
   PORT (
      clk        : IN     std_logic ;
      ienc       : IN     std_logic ;
      load       : IN     std_logic ;
      reg_out    : IN     std_logic_vector ( 127 DOWNTO 0 );
      shift_intr : IN     std_logic ;
      dec_a      : OUT    std_logic_vector (15 DOWNTO 0);
      dec_b      : OUT    std_logic_vector (15 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : dec_ctrl USE ENTITY my_project1_lib.dec_ctrl;
   FOR ALL : reg USE ENTITY my_project1_lib.reg;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : dec_ctrl
      PORT MAP (
         chipherd_in   => chipherd_in,
         clk           => clk,
         decipher_en   => decipher_en,
         from_aes      => from_aes,
         idec          => idec,
         intr_from_aes => intr_from_aes,
         ion           => ion,
         intr_to_aes   => intr_to_aes,
         load          => load,
         reg_out       => reg_out,
         shift_intr    => shift_intr,
         to_aes        => to_aes
      );
   U_1 : reg
      PORT MAP (
         clk        => clk,
         ienc       => ienc,
         load       => load,
         reg_out    => reg_out,
         shift_intr => shift_intr,
         dec_a      => dec_a,
         dec_b      => dec_b
      );

END struct;
